name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'poetry'
      
      - name: install
        run: |
          python --version
<<<<<<< HEAD
<<<<<<< HEAD
          python -m pip install poetry
=======
=======
>>>>>>> parent of 1fc62b7 (Update main.yml)
          python -m pip install setuptools
>>>>>>> parent of 1fc62b7 (Update main.yml)
          python -m pip install -r requirements.txt
          python -m pip install attrs
            
      - name: build 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          
          cd $GITHUB_WORKSPACE
          git init 
          git config user.name "Github Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          REPOSITORY_PATH="https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          git checkout master 
          jupyter-book build .
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_build/html
